trigger:
  branches:
    include:
    - main
    - develop
  paths:
    include:
    - src/Modules/Observations/**
    - src/Services/MAPP.Services.Observations/**
    - src/Services/genai/observations-ai/**
    - src/Web/observations-mfe/**
    - orchestration/MAPP.Observations.AppHost/**

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net9.0'
  dotNetVersion: '9.0.x'
  nodeVersion: '20.x'
  pythonVersion: '3.11'

stages:
- stage: Build
  displayName: 'Build Observations Domain'
  jobs:
  - job: BuildDotNet
    displayName: 'Build .NET Components'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET $(dotNetVersion)'
      inputs:
        version: '$(dotNetVersion)'

    - task: DotNetCoreCLI@2
      displayName: 'Restore Observations Domain'
      inputs:
        command: 'restore'
        projects: |
          src/Modules/Observations/**/*.csproj
          src/Services/MAPP.Services.Observations/*.csproj
          orchestration/MAPP.Observations.AppHost/*.csproj

    - task: DotNetCoreCLI@2
      displayName: 'Build Observations Domain'
      inputs:
        command: 'build'
        projects: |
          src/Modules/Observations/**/*.csproj
          src/Services/MAPP.Services.Observations/*.csproj
          orchestration/MAPP.Observations.AppHost/*.csproj
        arguments: '--configuration $(buildConfiguration) --no-restore'

    - task: DotNetCoreCLI@2
      displayName: 'Test Observations Domain'
      inputs:
        command: 'test'
        projects: 'src/Modules/Observations/**/*Tests.csproj'
        arguments: '--configuration $(buildConfiguration) --no-build --collect:"XPlat Code Coverage"'

    - task: DotNetCoreCLI@2
      displayName: 'Publish Observations API'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'src/Services/MAPP.Services.Observations/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/observations-api'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Observations API Artifacts'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/observations-api'
        artifactName: 'observations-api'

  - job: BuildPython
    displayName: 'Build Python AI Service'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python $(pythonVersion)'
      inputs:
        versionSpec: '$(pythonVersion)'

    - script: |
        cd src/Services/genai/observations-ai
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m py_compile main.py
      displayName: 'Install dependencies and compile Python'

    - task: ArchiveFiles@2
      displayName: 'Archive Python AI Service'
      inputs:
        rootFolderOrFile: 'src/Services/genai/observations-ai'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/observations-ai.zip'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Python AI Artifacts'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/observations-ai.zip'
        artifactName: 'observations-ai'

  - job: BuildAngular
    displayName: 'Build Angular MFE'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      displayName: 'Use Node $(nodeVersion)'
      inputs:
        versionSpec: '$(nodeVersion)'

    - script: |
        cd src/Web/observations-mfe
        npm ci
        npm run build --prod
      displayName: 'Build Angular MFE'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Angular MFE Artifacts'
      inputs:
        pathToPublish: 'src/Web/observations-mfe/dist'
        artifactName: 'observations-mfe'

- stage: Deploy_Staging
  displayName: 'Deploy to Staging'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  jobs:
  - deployment: DeployStaging
    displayName: 'Deploy Observations Domain to Staging'
    environment: 'observations-staging'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Observations API to Azure'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webApp'
              appName: 'mapp-observations-api-staging'
              package: '$(System.ArtifactsDirectory)/observations-api'

- stage: Deploy_Production
  displayName: 'Deploy to Production'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: DeployProduction
    displayName: 'Deploy Observations Domain to Production'
    environment: 'observations-production'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Observations API to Production'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webApp'
              appName: 'mapp-observations-api-prod'
              package: '$(System.ArtifactsDirectory)/observations-api'
