trigger:
  branches:
    include:
    - main
    - develop
  paths:
    include:
    - src/Modules/Reports/**
    - src/Services/MAPP.Services.Reports/**
    - src/Services/genai/reports-ai/**
    - src/Web/reports-mfe/**

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net9.0'
  dotNetVersion: '9.0.x'
  nodeVersion: '20.x'
  pythonVersion: '3.11'

stages:
- stage: Build
  displayName: 'Build Reports Domain'
  jobs:
  - job: BuildDotNet
    displayName: 'Build .NET Components'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET $(dotNetVersion)'
      inputs:
        version: '$(dotNetVersion)'

    - task: DotNetCoreCLI@2
      displayName: 'Restore Reports Domain'
      inputs:
        command: 'restore'
        projects: |
          src/Modules/Reports/**/*.csproj
          src/Services/MAPP.Services.Reports/*.csproj

    - task: DotNetCoreCLI@2
      displayName: 'Build Reports Domain'
      inputs:
        command: 'build'
        projects: |
          src/Modules/Reports/**/*.csproj
          src/Services/MAPP.Services.Reports/*.csproj
        arguments: '--configuration $(buildConfiguration) --no-restore'

    - task: DotNetCoreCLI@2
      displayName: 'Test Reports Domain'
      inputs:
        command: 'test'
        projects: 'src/Modules/Reports/**/*Tests.csproj'
        arguments: '--configuration $(buildConfiguration) --no-build --collect:"XPlat Code Coverage"'

    - task: DotNetCoreCLI@2
      displayName: 'Publish Reports API'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'src/Services/MAPP.Services.Reports/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/reports-api'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Reports API Artifacts'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/reports-api'
        artifactName: 'reports-api'

  - job: BuildPython
    displayName: 'Build Python AI Service'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python $(pythonVersion)'
      inputs:
        versionSpec: '$(pythonVersion)'

    - script: |
        cd src/Services/genai/reports-ai
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m py_compile main.py
      displayName: 'Install dependencies and compile Python'

    - task: ArchiveFiles@2
      displayName: 'Archive Python AI Service'
      inputs:
        rootFolderOrFile: 'src/Services/genai/reports-ai'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/reports-ai.zip'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Python AI Artifacts'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/reports-ai.zip'
        artifactName: 'reports-ai'

  - job: BuildAngular
    displayName: 'Build Angular MFE'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      displayName: 'Use Node $(nodeVersion)'
      inputs:
        versionSpec: '$(nodeVersion)'

    - script: |
        cd src/Web/reports-mfe
        npm ci
        npm run build --prod
      displayName: 'Build Angular MFE'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Angular MFE Artifacts'
      inputs:
        pathToPublish: 'src/Web/reports-mfe/dist'
        artifactName: 'reports-mfe'

- stage: Deploy_Staging
  displayName: 'Deploy to Staging'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  jobs:
  - deployment: DeployStaging
    displayName: 'Deploy Reports Domain to Staging'
    environment: 'reports-staging'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Reports API to Azure'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webApp'
              appName: 'mapp-reports-api-staging'
              package: '$(System.ArtifactsDirectory)/reports-api'

- stage: Deploy_Production
  displayName: 'Deploy to Production'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: DeployProduction
    displayName: 'Deploy Reports Domain to Production'
    environment: 'reports-production'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Reports API to Production'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webApp'
              appName: 'mapp-reports-api-prod'
              package: '$(System.ArtifactsDirectory)/reports-api'
