trigger:
  branches:
    include:
    - main
    - develop
  paths:
    include:
    - src/Modules/UserManagement/**
    - src/Services/MAPP.Services.UserManagement/**
    - src/Web/usermanagement-mfe/**

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net9.0'
  dotNetVersion: '9.0.x'
  nodeVersion: '20.x'

stages:
- stage: Build
  displayName: 'Build UserManagement Domain'
  jobs:
  - job: BuildDotNet
    displayName: 'Build .NET Components'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET $(dotNetVersion)'
      inputs:
        version: '$(dotNetVersion)'

    - task: DotNetCoreCLI@2
      displayName: 'Restore UserManagement Domain'
      inputs:
        command: 'restore'
        projects: |
          src/Modules/UserManagement/**/*.csproj
          src/Services/MAPP.Services.UserManagement/*.csproj

    - task: DotNetCoreCLI@2
      displayName: 'Build UserManagement Domain'
      inputs:
        command: 'build'
        projects: |
          src/Modules/UserManagement/**/*.csproj
          src/Services/MAPP.Services.UserManagement/*.csproj
        arguments: '--configuration $(buildConfiguration) --no-restore'

    - task: DotNetCoreCLI@2
      displayName: 'Test UserManagement Domain'
      inputs:
        command: 'test'
        projects: 'src/Modules/UserManagement/**/*Tests.csproj'
        arguments: '--configuration $(buildConfiguration) --no-build --collect:"XPlat Code Coverage"'

    - task: DotNetCoreCLI@2
      displayName: 'Publish UserManagement API'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'src/Services/MAPP.Services.UserManagement/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/usermanagement-api'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish UserManagement API Artifacts'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/usermanagement-api'
        artifactName: 'usermanagement-api'

  - job: BuildAngular
    displayName: 'Build Angular MFE'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      displayName: 'Use Node $(nodeVersion)'
      inputs:
        versionSpec: '$(nodeVersion)'

    - script: |
        cd src/Web/usermanagement-mfe
        npm ci
        npm run build --prod
      displayName: 'Build Angular MFE'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Angular MFE Artifacts'
      inputs:
        pathToPublish: 'src/Web/usermanagement-mfe/dist'
        artifactName: 'usermanagement-mfe'

- stage: Deploy_Staging
  displayName: 'Deploy to Staging'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  jobs:
  - deployment: DeployStaging
    displayName: 'Deploy UserManagement Domain to Staging'
    environment: 'usermanagement-staging'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy UserManagement API to Azure'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webApp'
              appName: 'mapp-usermanagement-api-staging'
              package: '$(System.ArtifactsDirectory)/usermanagement-api'

- stage: Deploy_Production
  displayName: 'Deploy to Production'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: DeployProduction
    displayName: 'Deploy UserManagement Domain to Production'
    environment: 'usermanagement-production'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy UserManagement API to Production'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webApp'
              appName: 'mapp-usermanagement-api-prod'
              package: '$(System.ArtifactsDirectory)/usermanagement-api'
